require 'rake'
require 'rspec/core/rake_task'
require_relative 'db/config'


desc "create the database"
task "db:create" do
  touch 'db/ar-story.sqlite3'
end

desc "drop the database"
task "db:drop" do
  rm_f 'db/ar-story.sqlite3'
end

desc "reload the database"
task "db:reload" => ["db:drop", "db:create", "db:migrate"] do
end

desc "Open console"
task "console" do
  exec("irb -r ./app/models/story.rb")
end


desc "migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
task "db:migrate" do
  ActiveRecord::Migrator.migrations_paths << File.dirname(__FILE__) + 'db/migrate'
  ActiveRecord::Migration.verbose = ENV["VERBOSE"] ? ENV["VERBOSE"] == "true" : true
  ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, ENV["VERSION"] ? ENV["VERSION"].to_i : nil) do |migration|
    ENV["SCOPE"].blank? || (ENV["SCOPE"] == migration.scope)
  end
end


desc 'Retrieves the current schema version number'
task "db:version" do
  puts "Current version: #{ActiveRecord::Migrator.current_version}"
end

desc "gets current timestamp for migrations"
task "timestamp" do
  puts Time.now.strftime("%Y%m%d%H%M%S")
end

desc "Run the specs"
RSpec::Core::RakeTask.new(:specs)

task :default  => :specs
